services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paza_event_api
    restart: always
    env_file:
      - .env
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - static_data:/app/static

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: paza_event_bot
    restart: always
    command: ["python", "run_bot.py"]
    env_file:
      - .env

volumes:
  static_data:
